project_name: go-test
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
  - id: darwin-build
    binary: go-test
    ldflags:
      - -s
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
  - id: linux-build
    binary: go-test
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - 386
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      amd64: amd64
release:
  prerelease: auto
