project_name: go-test
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: go-test
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_INCLUDE="-I/usr/include"
      - CGO_LDFLAGS="-L/usr/local/lib"
      - CC=aarch64-linux-gnu-gcc
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      amd64: x86_64
release:
  prerelease: auto
