project_name: go-test
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: go-test
    ldflags:
      - -s
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/plenti/plenti-osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/plenti/plenti-osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      amd64: x86_64
release:
  prerelease: auto
