name: release
on:
  push:
    tags:
      - "*"
jobs:
  goreleaser-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt -V install \
            gcc libc6-dev \
            libx11-dev xorg-dev libxtst-dev libpng++-dev \
            xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev \
            libxkbcommon-dev \
            xsel xclip \
            gobjc++ \
            g++-aarch64-linux-gnu \
            libc6-dev-arm64-cross
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --config .goreleaser-ubuntu.yml
        env:
          GITHUB_TOKEN: ${{ github.token }}
